CREATE TABLE KH_STUDENT (
	STD_NO NUMBER PRIMARY KEY,
	STD_NAME NVARCHAR2(5) NOT NULL,
	PERSONAL_NO VARCHAR2(14) UNIQUE,
	MAJOR NVARCHAR2(10) NOT NULL,
	ENT_DATE DATE DEFAULT SYSDATE,
	STATUS NVARCHAR2(10) CHECK(STATUS IN ('재학', '휴학')) 
);

--DROP TABLE KH_STUDENT; 

COMMENT ON COLUMN KH_STUDENT.STD_NO IS '학번';
COMMENT ON COLUMN KH_STUDENT.STD_NAME IS '이름';
COMMENT ON COLUMN KH_STUDENT.PERSONAL_NO IS '주민등록번호';
COMMENT ON COLUMN KH_STUDENT.MAJOR IS '전공';
COMMENT ON COLUMN KH_STUDENT.ENT_DATE IS '입학일';
COMMENT ON COLUMN KH_STUDENT.STATUS IS '학생 상태';

CREATE SEQUENCE SEQ_STD_NO;
--DROP SEQUENCE SEQ_STD_NO;

INSERT INTO KH_STUDENT 
VALUES(SEQ_STD_NO.NEXTVAL, '차붐근', '530522-1259847', '체육교육과', DEFAULT, '재학');
INSERT INTO KH_STUDENT 
VALUES(SEQ_STD_NO.NEXTVAL, '손흥만', '920708-1053411', '정치외교과', DEFAULT, '재학');
INSERT INTO KH_STUDENT 
VALUES(SEQ_STD_NO.NEXTVAL, '박지상', '810225-1205732', '영어영문학과', DEFAULT, '휴학');
INSERT INTO KH_STUDENT 
VALUES(SEQ_STD_NO.NEXTVAL, '김민제', '961115-1541183', '기계공학과', DEFAULT, '재학');
INSERT INTO KH_STUDENT 
VALUES(SEQ_STD_NO.NEXTVAL, '안정완', '760127-1030965', '방송연예과', DEFAULT, '휴학');
INSERT INTO KH_STUDENT 
VALUES(SEQ_STD_NO.NEXTVAL, '이형표', '770423-1453652', '기독교학과', DEFAULT, '휴학');
INSERT INTO KH_STUDENT 
VALUES(SEQ_STD_NO.NEXTVAL, '기숭용', '890124-1485711', '모델학과', DEFAULT, '재학');
INSERT INTO KH_STUDENT 
VALUES(SEQ_STD_NO.NEXTVAL, '이훈제', '730426-1342765', '식품영양학과', DEFAULT, '휴학');
INSERT INTO KH_STUDENT 
VALUES(SEQ_STD_NO.NEXTVAL, '김남이', '770501-1275932', '연극영화과', DEFAULT, '재학');
INSERT INTO KH_STUDENT 
VALUES(SEQ_STD_NO.NEXTVAL, '홍금보', '690212-1023472', '부동산학과', DEFAULT, '재학');
INSERT INTO KH_STUDENT 
VALUES(SEQ_STD_NO.NEXTVAL, '이간인', '010219-3086511', '불어불문학과', DEFAULT, '재학');

SELECT * FROM KH_STUDENT;

COMMIT;
